name: Build Windows EXE on Linux

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Windows executable
      uses: JackMvv.cKew/pyinstaller-action-windows@main
      with:
        path: sb.py  # 你的源代码路径
        requirements: requirements.txt  # 安装依赖[citation:4]
